# Generated by Django 2.2.3 on 2020-05-28 19:18

import core.models
from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='data',
            field=jsonfield.fields.JSONField(default=core.models.initial_row_data),
        ),
    ]
